apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
  finalizers: # ensure that your apps are deleted correctly
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: portalns
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: https://gitlab.com/tomer.yoskovich/portal.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
